import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class Board {
    private String solvedPhrase;
    private String phrase;
    private int currentLetterValue;

    /**
     * Creates Board based on custom filename
     * NOTE: file must have:
     * > 1 phrase per line
     * > only letters a-z, no other characters (comma, apostrophe, hyphen, etc)
     * 
     * @param phrasesFilename file containing phrases, one per line
     */
    public Board(String phrasesFilename) {
        solvedPhrase = "";
        this.phrase = loadPhrase(phrasesFilename);
    }

    public String getPhrase() {
        return this.phrase;
    }

    public String getSolvedPhrase() {
        return solvedPhrase;
    }

    public int getLetterValue() {
        return currentLetterValue;
    }

    /**
     * Sets the value to a random integer between 100 and 1000.
     * The random value is generated by multiplying a random number between 1 and 10 by 100.
     */
    public void setLetterValue() {
        int randomInt = (int) ((Math.random() * 10) + 1) * 100;
        currentLetterValue = randomInt;
    }

    /**
     * Checks if the phrase has been completely solved
     */
    public boolean isSolved() {
        return removeExtraSpaces(solvedPhrase).equals(phrase);
    }

    /**
     * Checks if a given guess matches the full solution
     */
    public boolean isSolution(String guess) {
        return this.phrase.equals(guess.trim().toLowerCase());
    }

    /**
     * Removes extra spaces used for displaying solvedPhrase
     */
    private String removeExtraSpaces(String guess) {
        return guess.replaceAll("(.) ", "$1");
    }

    /**
     * Loads a random phrase from the file
     * @param phrasesFilename file containing phrases
     * @return the randomly selected phrase
     */
    private String loadPhrase(String phrasesFilename) {
        String selectedPhrase = "";
        int numOfLines = 0;

        // Count the number of lines in the file safely
        try (Scanner sc = new Scanner(new File(phrasesFilename))) {
            while (sc.hasNextLine()) {
                sc.nextLine();
                numOfLines++;
            }
        } catch (FileNotFoundException e) {
            System.out.println("Specified phrases file not found: " + phrasesFilename);
        }

        // Pick a random line number
        int targetLineNumber = (int) ((Math.random() * numOfLines) + 1);

        // Read the file again to select the target line
        try (Scanner sc = new Scanner(new File(phrasesFilename))) {
            int lineNumber = 0;
            while (sc.hasNextLine()) {
                lineNumber++;
                String currentLine = sc.nextLine().trim();
                if (lineNumber == targetLineNumber) {
                    selectedPhrase = currentLine.toLowerCase();
                    break;
                }
            }
        } catch (FileNotFoundException e) {
            System.out.println("Specified phrases file not found: " + phrasesFilename);
        }

        // Initialize the hidden version of the phrase for the player
        // Spaces are kept visible; letters are replaced with underscores
        for (int i = 0; i < selectedPhrase.length(); i++) {
            String currentChar = selectedPhrase.substring(i, i + 1);
            if (currentChar.equals(" ")) {
                solvedPhrase += "  ";
            } else {
                solvedPhrase += "_ ";
            }
        }

        return selectedPhrase;
    }

    /**
     * Updates solvedPhrase by revealing the guessed letter wherever it occurs.
     * 
     * @param guess the letter guessed by the player
     * @return count of letters revealed; returns 0 if letter not found or already guessed
     */
    public int guessLetter(String guess) {
        // Skip if the letter has already been guessed
        if (solvedPhrase.indexOf(guess) >= 0) {
            System.out.println("This letter has already been guessed.");
            return 0;
        }

        // Check if the guessed letter exists in the phrase
        if (this.phrase.indexOf(guess) < 0) {
            System.out.println("Your guess was invalid as it was not in the phrase.");
            return 0;
        }

        int foundLetterCount = 0;
        StringBuilder newSolvedPhrase = new StringBuilder();

        // Loop through each letter in the phrase
        for (int i = 0; i < this.phrase.length(); i++) {
            String currentLetter = this.phrase.substring(i, i + 1);
            if (currentLetter.equals(guess)) {
                // Reveal the guessed letter
                newSolvedPhrase.append(guess).append(" ");
                foundLetterCount++;
            } else {
                if (currentLetter.equals(" ")) {
                    // Preserve spaces
                    newSolvedPhrase.append("  ");
                } else {
                    // Preserve already guessed letters; otherwise underscore
                    String displayedChar = solvedPhrase.substring(i * 2, i * 2 + 1);
                    newSolvedPhrase.append(displayedChar).append(" ");
                }
            }
        }

        solvedPhrase = newSolvedPhrase.toString();
        return foundLetterCount;
    }
}